### ISSUE TITLE
Unable to resolve "three/examples/jsm/loaders/ColladaLoader"

### ISSUE THREAD

**Issue by acondurache** [expo/expo-three#143]
I have been getting an error with new SDK 35 when importing expo-three. 

Error: **Unable to resolve "three/examples/jsm/loaders/ColladaLoader" from "node_modules\expo-three\build\loaders\loadModelsAsync.js"**

Package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "expo-graphics": "^1.1.0",
    "expo-three": "4.0.6",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-web": "^0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.1.0"
  },
  "private": true
}

```
Possibly related to issue [#126](https://github.com/expo/expo-three/issues/126) however downgrading expo-three to version 4x does not resolve the issue.

**Comment by funnyjerry** [comment]
Not working

**Comment by EvanBacon** [comment]
Fixed in 5.5.1

**Comment by nthatte** [comment]
I'm still seeing this issue with 5.5.1. For example, the snack linked to from here https://docs.expo.io/versions/latest/sdk/AR/  gives the error 
```
Device: (901:881) Unable to resolve module 'module://three/examples/jsm/loaders/ColladaLoader.js'
  Evaluating module://three/examples/jsm/loaders/ColladaLoader.js
  Evaluating module://expo-three.js
  Evaluating module://App.js.js
  Loading module://App.js
```
and has 5.5.1 listed in its dependencies.

**Comment by CarlosLanderas** [comment]
I'm also having the same problem using 5.5.1

**Comment by opexu** [comment]
same problem 5.5.1
